export interface Template {
  slug: string;
  title: string;
  description: string;
  h1: string;
  heroSubtitle: string;
  downloadUrl?: string;
  previewContent: string[];
  relatedSlugs: string[];
  primaryCtaText: string;
  primaryCtaHref: string;
}

export const templates: Template[] = [
  {
    slug: "seo-fix-list-30-minutes",
    title: "SEO Fix List (30 Minutes) | C&L Strategy",
    description: "Quick SEO fixes you can implement in 30 minutes. A checklist of high-impact improvements for immediate results.",
    h1: "SEO Fix List (30 Minutes)",
    heroSubtitle: "Quick wins that make a difference. Implement these fixes in 30 minutes.",
    previewContent: [
      "Check Google Business Profile completeness",
      "Verify title tags and meta descriptions",
      "Test mobile responsiveness",
      "Check page load speed",
      "Review internal linking structure",
      "Verify schema markup",
      "Check for broken links",
      "Review heading structure",
    ],
    relatedSlugs: ["seo-foundation-rebuild", "site-speed-and-core-web-vitals", "schema-and-entity-layer"],
    primaryCtaText: "Download Checklist",
    primaryCtaHref: "/contact",
  },
  {
    slug: "pseo-cluster-blueprint",
    title: "pSEO Cluster Blueprint | C&L Strategy",
    description: "A blueprint for building programmatic SEO clusters at scale. Template and framework for systematic page creation.",
    h1: "pSEO Cluster Blueprint",
    heroSubtitle: "Build programmatic SEO clusters systematically, not randomly.",
    previewContent: [
      "Template structure for programmatic pages",
      "Content variation rules",
      "Internal linking architecture",
      "Quality control checklist",
      "Expansion roadmap",
      "Performance monitoring framework",
    ],
    relatedSlugs: ["pseo-programmatic-pages", "how-to-build-city-pages", "service-page-cluster-build"],
    primaryCtaText: "Download Blueprint",
    primaryCtaHref: "/contact",
  },
  {
    slug: "service-page-copy-framework",
    title: "Service Page Copy Framework | C&L Strategy",
    description: "A framework for writing service pages that convert. Structure, messaging, and conversion elements.",
    h1: "Service Page Copy Framework",
    heroSubtitle: "Service pages that rank and convert, not generic pages that don't.",
    previewContent: [
      "Service page structure template",
      "Value proposition framework",
      "Problem-solution messaging",
      "CTA placement strategy",
      "Conversion optimization checklist",
      "SEO optimization guidelines",
    ],
    relatedSlugs: ["how-to-structure-service-pages", "service-page-cluster-build", "conversion-rate-optimization"],
    primaryCtaText: "Download Framework",
    primaryCtaHref: "/contact",
  },
  {
    slug: "ai-ready-faq-builder",
    title: "AI-Ready FAQ Builder | C&L Strategy",
    description: "A framework for writing FAQs that appear in AI search results. Answer Engine Optimization for FAQs.",
    h1: "AI-Ready FAQ Builder",
    heroSubtitle: "FAQs that AI systems select as answers, not generic Q&A that gets ignored.",
    previewContent: [
      "FAQ writing best practices",
      "Answer structure for AI",
      "FAQ schema implementation",
      "Voice search optimization",
      "AEO checklist",
      "FAQ expansion strategy",
    ],
    relatedSlugs: ["how-to-write-faqs-for-ai-results", "aeo-answer-engine-optimization", "faq-hub-build"],
    primaryCtaText: "Download Builder",
    primaryCtaHref: "/contact",
  },
  {
    slug: "local-seo-checklist",
    title: "Local SEO Checklist | C&L Strategy",
    description: "Complete local SEO checklist for dominating local search. Google Business Profile, citations, and local content.",
    h1: "Local SEO Checklist",
    heroSubtitle: "Own local search with this comprehensive checklist.",
    previewContent: [
      "Google Business Profile optimization",
      "Local citation building",
      "NAP consistency check",
      "Review generation strategy",
      "Local schema markup",
      "Location page optimization",
    ],
    relatedSlugs: ["local-search-domination", "near-me-query-capture", "city-page-cluster-build"],
    primaryCtaText: "Download Checklist",
    primaryCtaHref: "/contact",
  },
  {
    slug: "conversion-optimization-audit",
    title: "Conversion Optimization Audit | C&L Strategy",
    description: "Audit your site's conversion potential. Checklist for identifying and fixing conversion barriers.",
    h1: "Conversion Optimization Audit",
    heroSubtitle: "Find and fix conversion barriers systematically.",
    previewContent: [
      "Conversion funnel analysis",
      "CTA audit checklist",
      "Form optimization review",
      "Mobile conversion check",
      "Trust signal audit",
      "User experience review",
    ],
    relatedSlugs: ["conversion-rate-optimization", "proposal-site-that-closes", "landing-page-factory"],
    primaryCtaText: "Download Audit",
    primaryCtaHref: "/contact",
  },
  {
    slug: "content-strategy-template",
    title: "Content Strategy Template | C&L Strategy",
    description: "A template for building a content strategy that drives results. Editorial calendar, topic research, and distribution.",
    h1: "Content Strategy Template",
    heroSubtitle: "Build a content strategy that works, not a content calendar that sits unused.",
    previewContent: [
      "Content strategy framework",
      "Editorial calendar template",
      "Topic research process",
      "Content distribution plan",
      "Performance tracking setup",
      "Content optimization workflow",
    ],
    relatedSlugs: ["content-engine-90-days", "inbound-lead-system", "authority-building-plan"],
    primaryCtaText: "Download Template",
    primaryCtaHref: "/contact",
  },
  {
    slug: "landing-page-template",
    title: "Landing Page Template | C&L Strategy",
    description: "Conversion-optimized landing page template. Structure, copy framework, and design guidelines.",
    h1: "Landing Page Template",
    heroSubtitle: "Landing pages that convert, built fast and at scale.",
    previewContent: [
      "Landing page structure",
      "Headline frameworks",
      "Value proposition templates",
      "CTA placement guide",
      "Form optimization",
      "Mobile-first design guidelines",
    ],
    relatedSlugs: ["landing-page-factory", "conversion-rate-optimization", "proposal-site-that-closes"],
    primaryCtaText: "Download Template",
    primaryCtaHref: "/contact",
  },
  {
    slug: "seo-audit-template",
    title: "SEO Audit Template | C&L Strategy",
    description: "Comprehensive SEO audit template. Technical SEO, content, and off-page factors.",
    h1: "SEO Audit Template",
    heroSubtitle: "Audit your SEO foundation systematically.",
    previewContent: [
      "Technical SEO checklist",
      "Content audit framework",
      "Link analysis process",
      "Competitor analysis template",
      "Keyword research framework",
      "Reporting template",
    ],
    relatedSlugs: ["seo-foundation-rebuild", "competitive-gap-audit", "site-speed-and-core-web-vitals"],
    primaryCtaText: "Download Template",
    primaryCtaHref: "/contact",
  },
  {
    slug: "case-study-template",
    title: "Case Study Template | C&L Strategy",
    description: "A template for writing case studies that build trust and convert. Structure, storytelling, and conversion elements.",
    h1: "Case Study Template",
    heroSubtitle: "Case studies that showcase your work effectively.",
    previewContent: [
      "Case study structure",
      "Storytelling framework",
      "Results presentation",
      "Visual element guide",
      "Conversion optimization",
      "Distribution strategy",
    ],
    relatedSlugs: ["case-study-engine", "proposal-site-that-closes", "authority-building-plan"],
    primaryCtaText: "Download Template",
    primaryCtaHref: "/contact",
  },
];
